package api.pojo;

import org.mavlink.messages.MAV_MODE_FLAG;

import main.Text;

/** UAV flight modes available.
 * <p>Developed by: Francisco Jos&eacute; Fabra Collado, from GRC research group in Universitat Polit&egrave;cnica de Val&egrave;ncia (Valencia, Spain).</p> */

public enum FlightMode {
	/** Self-levels the roll and pitch axis. */
	STABILIZE(MAV_MODE_FLAG.MAV_MODE_FLAG_MANUAL_INPUT_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_STABILIZE_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_CUSTOM_MODE_ENABLED,
			0, Text.STABILIZE),
	/** Self-levels the roll and pitch axis. Engines are spinning. */
	STABILIZE_ARMED(MAV_MODE_FLAG.MAV_MODE_FLAG_SAFETY_ARMED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_MANUAL_INPUT_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_STABILIZE_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_CUSTOM_MODE_ENABLED, // only 209, not as the rest (217)
			0, Text.STABILIZE_ARMED),
	/** Navigates to single points commanded by GCS. */
	GUIDED(MAV_MODE_FLAG.MAV_MODE_FLAG_MANUAL_INPUT_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_STABILIZE_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_GUIDED_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_CUSTOM_MODE_ENABLED,
			4, Text.GUIDED),
	/** Navigates to single points commanded by GCS. Engines are spinning. */
	GUIDED_ARMED(MAV_MODE_FLAG.MAV_MODE_FLAG_SAFETY_ARMED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_MANUAL_INPUT_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_STABILIZE_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_GUIDED_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_CUSTOM_MODE_ENABLED,
			4, Text.GUIDED_ARMED),
	/** Executes pre-defined mission. */
	AUTO(MAV_MODE_FLAG.MAV_MODE_FLAG_MANUAL_INPUT_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_STABILIZE_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_GUIDED_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_CUSTOM_MODE_ENABLED,
			3, Text.AUTO),
	/** Executes pre-defined mission. Engines are spinning. */
	AUTO_ARMED(MAV_MODE_FLAG.MAV_MODE_FLAG_SAFETY_ARMED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_MANUAL_INPUT_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_STABILIZE_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_GUIDED_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_CUSTOM_MODE_ENABLED,
			3, Text.AUTO_ARMED),
	/** Holds altitude and position, uses GPS for movements. */
	LOITER(MAV_MODE_FLAG.MAV_MODE_FLAG_MANUAL_INPUT_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_STABILIZE_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_GUIDED_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_CUSTOM_MODE_ENABLED,
			5, Text.LOITER),
	/** Holds altitude and position, uses GPS for movements. Engines are spinning. */
	LOITER_ARMED(MAV_MODE_FLAG.MAV_MODE_FLAG_SAFETY_ARMED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_MANUAL_INPUT_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_STABILIZE_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_GUIDED_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_CUSTOM_MODE_ENABLED,
			5, Text.LOITER_ARMED),
	/** Returns above takeoff location, may also include landing. */
	RTL(MAV_MODE_FLAG.MAV_MODE_FLAG_MANUAL_INPUT_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_STABILIZE_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_GUIDED_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_CUSTOM_MODE_ENABLED,
			6, Text.RTL),
	/** Returns above takeoff location, may also include landing. Engines are spinning. */
	RTL_ARMED(MAV_MODE_FLAG.MAV_MODE_FLAG_SAFETY_ARMED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_MANUAL_INPUT_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_STABILIZE_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_GUIDED_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_CUSTOM_MODE_ENABLED,
			6, Text.RTL_ARMED),
	/** Automatically circles a point in front of the vehicle. */
	CIRCLE(MAV_MODE_FLAG.MAV_MODE_FLAG_MANUAL_INPUT_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_STABILIZE_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_GUIDED_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_CUSTOM_MODE_ENABLED,
			7, Text.CIRCLE),
	/** Automatically circles a point in front of the vehicle. Engines are spinning. */
	CIRCLE_ARMED(MAV_MODE_FLAG.MAV_MODE_FLAG_SAFETY_ARMED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_MANUAL_INPUT_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_STABILIZE_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_GUIDED_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_CUSTOM_MODE_ENABLED,
			7, Text.CIRCLE_ARMED),
	/** Like loiter, but manual roll and pitch when sticks not centered. */
	POSHOLD(MAV_MODE_FLAG.MAV_MODE_FLAG_MANUAL_INPUT_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_STABILIZE_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_GUIDED_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_CUSTOM_MODE_ENABLED,
			16, Text.POSHOLD),
	/** Like loiter, but manual roll and pitch when sticks not centered. Engines are spinning. */
	POSHOLD_ARMED(MAV_MODE_FLAG.MAV_MODE_FLAG_SAFETY_ARMED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_MANUAL_INPUT_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_STABILIZE_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_GUIDED_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_CUSTOM_MODE_ENABLED,
			16, Text.POSHOLD_ARMED),
	/** Brings copter to an immediate stop. */
	BRAKE(MAV_MODE_FLAG.MAV_MODE_FLAG_MANUAL_INPUT_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_STABILIZE_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_GUIDED_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_CUSTOM_MODE_ENABLED,
			17, Text.BRAKE),
	/** Brings copter to an immediate stop. Engines are spinning. */
	BRAKE_ARMED(MAV_MODE_FLAG.MAV_MODE_FLAG_SAFETY_ARMED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_MANUAL_INPUT_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_STABILIZE_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_GUIDED_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_CUSTOM_MODE_ENABLED,
			17, Text.BRAKE_ARMED),
	/** Avoid collisions using ADS-B sensor, if properly configured. */
	AVOID_ADSB(MAV_MODE_FLAG.MAV_MODE_FLAG_MANUAL_INPUT_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_STABILIZE_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_GUIDED_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_CUSTOM_MODE_ENABLED,
			19, Text.AVOID_ADSB),
	/** Avoid collisions using ADS-B sensor, if properly configured. Engines are spinning. */
	AVOID_ADSB_ARMED(MAV_MODE_FLAG.MAV_MODE_FLAG_SAFETY_ARMED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_MANUAL_INPUT_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_STABILIZE_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_GUIDED_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_CUSTOM_MODE_ENABLED,
			19, Text.AVOID_ADSB_ARMED),
	/** Reduces altitude to ground level, attempts to go straight down. */
	LAND(MAV_MODE_FLAG.MAV_MODE_FLAG_MANUAL_INPUT_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_STABILIZE_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_CUSTOM_MODE_ENABLED,
			9, Text.LAND),
	/** Reduces altitude to ground level, attempts to go straight down. Engines are spinning. */
	LAND_ARMED(MAV_MODE_FLAG.MAV_MODE_FLAG_SAFETY_ARMED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_MANUAL_INPUT_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_STABILIZE_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_CUSTOM_MODE_ENABLED,
			9, Text.LAND_ARMED),
	/** Holds position after a throwing takeoff. */
	THROW(MAV_MODE_FLAG.MAV_MODE_FLAG_MANUAL_INPUT_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_STABILIZE_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_CUSTOM_MODE_ENABLED,
			18, Text.THROW),
	/** Like stabilize, but coordinates yaw with roll like a plane. */
	DRIFT(MAV_MODE_FLAG.MAV_MODE_FLAG_MANUAL_INPUT_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_STABILIZE_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_CUSTOM_MODE_ENABLED,
			11, Text.DRIFT),
	/** Holds altitude and self-levels the roll & pitch. */
	ALT_HOLD(MAV_MODE_FLAG.MAV_MODE_FLAG_MANUAL_INPUT_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_STABILIZE_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_CUSTOM_MODE_ENABLED,
			2, Text.ALT_HOLD),
	/** Holds altitude and self-levels the roll & pitch. Engines are spinning. */
	ALT_HOLD_ARMED(MAV_MODE_FLAG.MAV_MODE_FLAG_SAFETY_ARMED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_MANUAL_INPUT_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_STABILIZE_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_CUSTOM_MODE_ENABLED,
			2, Text.ALT_HOLD),
	/** Alt-hold, but holds pitch & roll when sticks centered. */
	SPORT(MAV_MODE_FLAG.MAV_MODE_FLAG_MANUAL_INPUT_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_STABILIZE_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_CUSTOM_MODE_ENABLED,
			13, Text.SPORT),
	/** Holds attitude, no self-level. */
	ACRO(MAV_MODE_FLAG.MAV_MODE_FLAG_MANUAL_INPUT_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_STABILIZE_ENABLED
			+ MAV_MODE_FLAG.MAV_MODE_FLAG_CUSTOM_MODE_ENABLED,
			1, Text.ACRO);

	private final int baseMode;
	private final int customMode;
	private final String modeName;

	private FlightMode(int baseMode, int customMode, String modeName) {
		this.baseMode = baseMode;
		this.customMode = customMode;
		this.modeName = modeName;
	}

	public int getBaseMode() {
		return baseMode;
	}

	public int getCustomMode() {
		return customMode;
	}
	
	public String getMode() {
		return modeName;
	}

	/**
	 * Return the ardupilot flight mode corresponding to the base and custom values.
	 * <p>If no valid flight mode is found, it returns null.</p> */
	public static FlightMode getMode(int base, long custom) {
		for (FlightMode p : FlightMode.values()) {
			if (p.baseMode == base && p.customMode == custom) {
				return p;
			}
		}
		return null;
	}
}
